src/carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home,
    cart_update,
    checkout_home,
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]

src/marketplace/urls.py
from django.conf.urls import url, include
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView

from django.conf import settings
from django.conf.urls.static import static

from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view
from .views import HomeView, AboutView, TermsView, PolicyView, contact
from marketing.views import email_list_signup, MarketingPreferenceUpdateView
from .sitemaps import (
    CategorySitemap,
    CollectionSitemap,
    SubcategorySitemap,
    ProductSitemap,
    StaticViewSitemap
)

sitemaps = {
    'categories': CategorySitemap,
    'collections': CollectionSitemap,
    'subcategories': SubcategorySitemap,
    'products': ProductSitemap,
    'pages': StaticViewSitemap,
}


urlpatterns = [
    # url(r'^$', home, name='home'),
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^terms/$', TermsView.as_view(), name='terms'),
    url(r'^policy/$', PolicyView.as_view(), name='policy'),
    url(r'sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^subcategories/', include("categories.sub_urls", namespace='subcategories')),
    url(r'^categories/', include("categories.urls", namespace='categories')),
    url(r'^collections/', include("selections.urls", namespace='collections')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^contact/$', contact, name='contact'),
    url(r'^subscribe/$', email_list_signup, name='subscribe'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create_view'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^seller/', include("sellers.urls", namespace='sellers')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj  = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj  = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user      = models.ForeignKey(User, null=True, blank=True)
    products  = models.ManyToManyField(Product, blank=True)
    subtotal  = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total     = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    update    = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active    = models.BooleanField(default=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = float(instance.subtotal) * float(1.08) #8% Tax
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect

from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address

from billing.models import BillingProfile
from orders.models import Order
from .models import Cart
from products.models import Product


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'carts/home.html', {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        product_obj = Product.objects.get(id=product_id)
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session["cart_items"] = 0
            del request.session['cart_id']
            return redirect("/cart/succes")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }
    return render(request, 'carts/checkout.html', context)

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
{% if not billing_profile %}
    <div class="row text-center mt-5">
      <div class="col-6">
        <p class="lead">Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
      </div>
      <div class="col-6">
        <p class="lead">Continue as quest</p>
        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
      </div>
    </div>
{% else %}
  {% if not object.shipping_address %}
  <div class="container">
    <div class="row">
      <div class="col-12 mt-5">
        <p class="lead">Shipping address</p>
          <div class="col-6">
            {% url "checkout_address_create_view" as checkout_address_create_view %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_view address_type='shipping' %}
          </div>
          <div class="col-6">
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri %}
          </div>
      </div>
    </div>
  {% elif not object.billing_address %}
      <div class="row">
        <div class="col-12">
          <p class="lead">Billing address</p>
            {% url "checkout_address_create_view" as checkout_address_create_view %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create_view address_type='billing' %}
        </div>
      </div>
    {% else %}
      <div class="row">
        <div class="col-12 mt-5">
          <h3 class="text-center">Finalize Checkout</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-12 mt-5">
          <p>Cart total: $ {{ object.cart.total }}</p>
          <p>Shipping total: $ {{ object.shipping_total }}</p>
          <p>Order total: $ {{ object.total }}</p>
        </div>
      </div>
      </div>
    {% endif %}
  </div>
  {% endif %}
{% endblock %}

src/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12 mt-5">
      <h3 class="text-center">Cart</h3>
    </div>
  </div>
  {% if cart.products.exists %}
    <div class="row">
      <div class="col-12 mt-5">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Product SKU</th>
              <th scope="col">Product name</th>
              <th scope="col">Short description</th>
              <th scope="col">Product price</th>
            </tr>
          </thead>
          <tbody>
            {% for product in cart.products.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
              </td>
              <td>{{ product.short_description }}</td>
              <td>$ {{ product.price }}</td>
            </tr>
            {% endfor %}
            <tr>
              <td colspan="3"></td>
              <td><b>Subtotal:</b> {{ cart.subtotal }} $</td>
            </tr>
            <tr>
              <td colspan="3"></td>
              <td><b>Total:</b> {{ cart.total }} $</td>
            </tr>
            <tr>
              <td colspan="3"></td>
              <td><a class="btn btn-success" href="{% url 'cart:checkout' %}">Checkout</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  {% else %}
  <p class="lead">Cart is empty</p>
  {% endif %}
</div>

{% endblock %}